apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/clegginabox/homelab
    path: k8s/apps/metallb
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
