apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest-tracker
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/clegginabox/homelab
    path: k8s/apps/speedtest-tracker
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
