apiVersion: v1
kind: Service
metadata:
  labels:
    app: speedtest-tracker
  name: speedtest-tracker
  namespace: default
spec:
  selector:
    app: speedtest-tracker
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


