apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
  namespace: metallb-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb-controller
  template:
    metadata:
      labels:
        app: metallb-controller
    spec:
      containers:
        - name: metallb-controller
          image: metallb/controller:v0.13.3
          ports:
            - containerPort: 7472
          volumeMounts:
            - name: config
              mountPath: /etc/metallb
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: metallb-config  # Link to the ConfigMap you created
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-speaker
  namespace: metallb-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb-speaker
  template:
    metadata:
      labels:
        app: metallb-speaker
    spec:
      containers:
        - name: metallb-speaker
          image: metallb/speaker:v0.13.3
          ports:
            - containerPort: 7472
          volumeMounts:
            - name: config
              mountPath: /etc/metallb
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: metallb-config  # Link to the ConfigMap you created
---
apiVersion: v1
kind: Service
metadata:
  name: metallb-controller
  namespace: metallb-system
spec:
  ports:
    - port: 7472
      targetPort: 7472
  selector:
    app: metallb-controller
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-config
  namespace: metallb-system
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.5.100-192.168.5.200
